export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
<<<<<<< HEAD
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
=======
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
>>>>>>> 6d43a92140da87e06fe716f6d1fa5d5deb4f17a6
